(("default" . ((user-emacs-directory . "~/Documents/misc/emacs/doom-emacs")))
 ("spacemacs" . ((user-emacs-directory . "~/Documents/misc/emacs/spacemacs")))
 ("prelude" . ((user-emacs-directory . "~/Documents/misc/emacs/prelude")))
 ("centaur" . ((user-emacs-directory . "~/Documents/misc/emacs/centaur")))
 ("scimax" . ((user-emacs-directory . "~/Documents/misc/emacs/scimax")))
 ("vanilla" . ((user-emacs-directory . "~/.emacs.d"))))
